<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/Trainers_notes/Machine_Learning/MarkovChain_Aisha(03_10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Your future will depend on Present Not on Past**

# What is a Markov Chain?

**A Markov Chain is a sequence of events where the outcome of the next event depends only on the current state, not on the sequence of events that preceded it.**

**This is called the memoryless property.**

These probabilities form a system where the future depends only on the present , not on what happened yesterday or earlier.

#Key Components of a Markov Chain

**States:**

The possible conditions or outcomes in the system.

**Transition Probabilities:**

The likelihood of moving from one state to another.
Represented as numbers between 0 and 1.

**Transition Matrix:**

A table showing the probabilities of transitioning between states.

# How Does a Markov Chain Work?

**1) Starting State:**

Begin with an initial state .

**2) Transition:**

Use probabilities to determine the next state.

**3) Repeat the Process:**

Keep transitioning for the desired number of steps (e.g., 10 days).

In [ ]:
#Dataset Link https://drive.google.com/file/d/1g7RmS0PaKkjNIfYc2AwHjJIkeWbOgn70/view?usp=sharing

Markovify is a simple, extensible Markov chain generator. Right now, its main use is for building Markov models of large corpora of text, and generating random sentences from that. But, in theory, it could be used for other applications.

About the Dataset: This includes the entire corpus of articles published by the ABC website in the given time range. With a volume of 200 articles per day and a good focus on international news, we can be fairly certain that every event of significance has been captured here. This dataset can be downloaded from Kaggle Datasets.

In [ ]:
#Reinforcement learning: the models get better with usage(on the basis of input and overcoming their own errors)

In [ ]:
import numpy as np
import pandas as pd
import random
import markovify as mv

In [ ]:
!pip install markovify

Requirement already satisfied: markovify in /usr/local/lib/python3.12/dist-packages (0.9.4)
Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (from markovify) (1.4.0)

In [ ]:
df=pd.read_csv('/content/abcnews-date-text (1).csv')

In [ ]:
df

         publish_date                                      headline_text
0            20030219  aba decides against community broadcasting lic...
1            20030219     act fire witnesses must be aware of defamation
2            20030219     a g calls for infrastructure protection summit
3            20030219           air nz staff in aust strike for pay rise
4            20030219      air nz strike to affect australian travellers
...               ...                                                ...
1244179      20211231  two aged care residents die as state records 2...
1244180      20211231  victoria records 5;919 new cases and seven deaths
1244181      20211231    wa delays adopting new close contact definition
1244182      20211231  western ringtail possums found badly dehydrate...
1244183      20211231  what makes you a close covid contact here are ...

[1244184 rows x 2 columns]

In [ ]:
# df.sample(5)

In [ ]:
df['headline_text'][random.sample(range(50),5)]

44               england change three for wales match
20    businesses should prepare for terrorist attacks
43     dying korean subway passengers phoned for help
23             carews freak goal leaves roma in ruins
9          australia is locked into war timetable opp
Name: headline_text, dtype: object

In [ ]:
#NewlineText is training the model to find patterns between 2 words(state_size, could be more)
#state_size => number of current state we'll be using

In [ ]:
text_model1=mv.NewlineText(df['headline_text'],state_size=2)

In [ ]:
text_model1.make_sentence()

'council company to discuss indonesia prisoner'

In [ ]:
text_model2=mv.NewlineText(df['headline_text'],state_size=3)

In [ ]:
text_model2.make_sentence()

'gillard surges ahead as greens lose favour'

In [ ]:
text_model3=mv.NewlineText(df['headline_text'],state_size=4)

In [ ]:
text_model3.make_sentence()

'chakvetadze forced to retire in sydney to hobart sail down nsw coast'

In [ ]:
# for i in range(10):
#   i=text_model3.make_sentence()
#   print(i)

In [ ]:
text_model4=mv.NewlineText(df['headline_text'],state_size=3)

In [ ]:
text_model5=mv.NewlineText(df['headline_text'],state_size=3)

In [ ]:
#when combining models, the STATE SIZE should be same
combined_model=mv.combine([text_model2,text_model4],[1,1.5])

In [ ]:
combined_model.make_sentence()

'medical files dropped on busy canberra road'

**Weakeness**
- Short memory: cant capture long term context
- Data Sparsity: needs probabilities for every possible sequences
- Not good with high dimensional/complex data