<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/My_Live_Handson/Statistics/Statistics_handson_by_me_(19%2C20_June).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
population = pd.Series(range(1,101))

In [ ]:
population

0       1
1       2
2       3
3       4
4       5
     ...
95     96
96     97
97     98
98     99
99    100
Length: 100, dtype: int64

In [ ]:
random_sample = population.sample(10, random_state=100).reset_index(drop=True)

In [ ]:
random_sample

0    38
1    63
2    27
3    42
4    36
5    26
6    37
7    34
8    78
9    22
dtype: int64

In [ ]:
for _ in range(1,6):
  print(type(_))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

## Day 2

In [1]:
import numpy as np
from statistics import mean,median,mode
data=[10,20,20,25,30,30,30,35,40,100]
avg=np.sum(data)/len(data)
print(avg)
print("Mean", mean(data))
sortedData=sorted(data)
mid=len(sortedData)//2
print(mid)
print(sortedData[mid])
print("Median", median(data))

34.0
Mean 34
5
30
Median 30.0

In [6]:
dict1 = {}

for i in data:
  dict1[i] = dict1.get(i, 0) + 1

max(dict1, key=dict1.get)

30

In [8]:
# others code

mode_data = max((data.count(item), item) for item in set(data))[1]
print("Mode of data: ",mode_data)

Mode of data:  30

In [10]:
((data.count(item), item) for item in set(data))